version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser"]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"
enabled = true