image: gitlab/gitlab-runner:latest

stages:
  - build
  - deploy

before_script:
  - echo "Start CI"
  - java --version
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - chmod +x devops/ci/build.sh
    - cd devops/ci
    - bash build.sh
  artifacts:
    paths:
      - backend/**/build/libs/*.jar
    expire_in: 3 days
  only:
    - main
  rules:
    - changes:
        - backend/**/*.{java}
        - backend/**/Dockerfile
        - frontend/**/*.{js,jsx,ts,tsx}
        - frontend/**/Dockerfile

deploy:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - docker login registry.gitlab.com -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - chmod +x devops/ci/deploy.sh
    - cd devops/ci
    - bash deploy.sh
  only:
    - main
  rules:
    - changes:
        - backend/**/*.{java}
        - backend/**/Dockerfile
        - frontend/**/*.{js,jsx,ts,tsx}
        - frontend/**/Dockerfile

after_script:
  - echo "End CI"
