image: gitlab/gitlab-runner:latest

stages:
  - build

before_script:
  - echo "Start CI"
  - java --version
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - chmod +x devops/ci/build.sh
    - cd devops/ci
    - bash build.sh
  artifacts:
    paths:
      - backend/**/build/libs/*.jar
    expire_in: 3 days
  only:
    - main

after_script:
  - echo "End CI"