image: java:17-jdk

stages:
  - build

before_script:
  - echo "Start CI"
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - devops/ci/build.sh
  only:
    - main

after_script:
  - echo "End CI"