image: java:17-jdk

stages:
  - build

before_script:
  - echo "Start CI"
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

after_script:
  - echo "End CI"