apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(api|ws)/.*
            pathType: Prefix
            backend:
              service:
                name: gateway-{{ .Release.Name }}-service
                port:
                  number: 8080
          - path: /.*
            pathType: Prefix
            backend:
              service:
                name: web-{{ .Release.Name }}-service
                port:
                  number: 3000