image:
  name: registry.digitalocean.com/cs-dev-registry/community-space
  tag: web-latest
  pullSecrets: repository-credentials
  pullPolicy: Always

service:
  ports:
    - name: http
      port: 3000
  type: ClusterIP

replicas: 1

env:
  NEXT_PUBLIC_CS_GATEWAY_URL: ''
  NEXT_PUBLIC_CS_GATEWAY_WS: ''

nextjsEnv: |-
  NEXT_PUBLIC_CS_GATEWAY_URL=
  NEXT_PUBLIC_CS_GATEWAY_WS=

secrets: [ ]
