apiVersion: v1
kind: Secret
metadata:
  name: mongo-key
type: Opaque
data:
  mongodb-keyfile: UTBoQlRrZEZUVVZEU0VGT1IwVk5SVU5JUVU1SFJVMUYK
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  username: {{ "mongoadmin" | b64enc }}
  password: {{ "adminpassword" | b64enc }}