image:
  name: registry.gitlab.com/rockdonald2/community-space
  tag: hub-mgmt-latest
  pullSecrets: repository-credentials
  pullPolicy: Always

service:
  ports:
    - name: http
      port: 8084
  type: ClusterIP

replicas: 1

resources:
  limits:
    cpu: 250m
    memory: 500Mi

hpa:
  targetCpuUtilization: 75
  minReplicas: 1
  maxReplicas: 1

liveness:
  path: /actuator/health/liveness
  port: 8084
readiness:
  path: /actuator/health/readiness
  port: 8084

env:
  SPRING_DATA_MONGODB_USERNAME: mongoadmin
  SPRING_DATA_MONGODB_DATABASE: hub-mgmt
  SPRING_DATA_MONGODB_HOST: mongodb-community-space-service.community-space.svc.cluster.local
  SPRING_DATA_REDIS_HOST: community-space-redis-master
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "community-space-kafka-headless.community-space.svc.cluster.local:9092"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS: always
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE: "redis, diskSpace, mongo, ping"
  MANAGEMENT_ENDPOINT_HEALTH_GROUP_LIVENESS_INCLUDE: "redis, diskSpace, mongo, ping"

secrets:
  - envName: SPRING_DATA_MONGODB_PASSWORD
    secretName: hub-mgmt-mongodb-password
    secretValue: "adminpassword"
