name: continuous-integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Adopt JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with internal script
        run: |
          chmod +x devops/ci/build.sh
          bash devops/ci/build.sh
      - name: Test with internal script
        run: |
          chmod +x devops/ci/test.sh
          bash devops/ci/test.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            backend/**/build/libs/*.jar