name: continuous-integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Set up Adopt JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: frontend/community-space/package-lock.json
      - name: Add git safe.directory for container
        run: |
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\ndirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
      - name: Build all projects with internal script
        run: |
          chmod +x devops/ci/build.sh
          cd devops/ci
          bash build.sh
          cd ../..
      - name: Test all projects with internal script
        run: |
          chmod +x devops/ci/test.sh
          cd devops/ci
          bash test.sh
          cd ../..
      - name: Send Memo-Mgmt code coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java
          coverage-file: backend/memo-mgmt/memo-mgmt/build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.MEMO_MGMT_DEEPSOURCE_DSN }}
      - name: Send Hub-Mgmt code coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java
          coverage-file: backend/hub-mgmt/hub-mgmt/build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.HUB_MGMT_DEEPSOURCE_DSN }}
      - name: Send Gateway code coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java
          coverage-file: backend/gateway/gateway/build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.GATEWAY_DEEPSOURCE_DSN }}
      - name: Send Activity-Notifications-Mgmt code coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java
          coverage-file: backend/activity-notifications-mgmt/activity-notifications-mgmt/build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.ACTIVITY_NOTIFICATIONS_MGMT_DEEPSOURCE_DSN }}
      - name: Send Account-Mgmt code coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java
          coverage-file: backend/account-mgmt/account-mgmt/build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.ACCOUNT_MGMT_DEEPSOURCE_DSN }}
      - name: Send front-end code coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: javascript
          coverage-file: frontend/community-space/coverage/lcov.info
          dsn: ${{ secrets.FRONTEND_DEEPSOURCE_DSN }}
